### ISSUE TITLE
Choosing Relevant Features

### ISSUE THREAD

**Issue by TaihuaLi** [TaihuaLi/NPDB_Data#1]
Selecting which attributes to include in analysis.

**Comment by TrishL** [comment]
See [Wiki page ](https://github.com/TaihuaLi/NPDB_Data/wiki/Variables-for-Dataset) for my list of recommendations.

I also created [another page ](https://github.com/TaihuaLi/NPDB_Data/wiki/Links-to-NPDB-Guides-and-Info) with links to the data definitions.
